server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.95.133:3306/order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  #格式化日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm
#启动mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.iflytek.enums #枚举类包
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iflytek.pojo #所有实体类别名类所在包